name: Build sail-riscv

runs:
  using: composite
  steps:
    - id: cache-sail-riscv
      uses: actions/cache@v3
      with:
        path: .sail
        key: sail-riscv-${{ runner.os }}

    - shell: bash
      if: steps.cache-sail-riscv.outputs.cache-hit != 'true'
      run: |
        wget https://github.com/rems-project/sail/releases/download/0.19.1-linux-binary/sail.tar.gz
        mkdir sail_0_19_1
        tar -xzf sail.tar.gz -C sail_0_19_1
        echo "$(pwd)/sail_0_19_1/sail/bin/" >> $GITHUB_PATH 
        git clone --recursive https://github.com/rems-project/sail-riscv.git .sail
        sudo apt install -y build-essential libgmp-dev z3 pkg-config zlib1g-dev
        cd .sail
        git checkout tags/0.8
        ./build_simulators.sh
        cd ..

    - shell: bash
      run: echo "$(pwd)/.sail/c_emulator" >> $GITHUB_PATH

