name: Download OSS CAD Suite

inputs:
  from_url:
    description: 'latest release cached'
    required: true

runs:
  using: composite
  steps:
    - id: cache-oss-cad
      uses: actions/cache@v3
      with:
        path: .oss-cad-suite
        key: oss-cad-suite-${{ runner.os }}-${{ inputs.from_url }}

    - shell: bash
      if: steps.cache-oss-cad.outputs.cache-hit != 'true'
      run: |
        wget -q -O - ${{ inputs.from_url }} | tar -zx --transform "s/oss-cad-suite/.oss-cad-suite"

    - shell: bash
      run: echo "$(pwd)/oss-cad-suite/bin" >> $GITHUB_PATH