name: fazyrv
compiler_exe: riscv32-unknown-elf-gcc
objdump_exe: riscv32-unknown-elf-objdump
ref_model_exe: sail_riscv_sim
udb_config: fazyrv.yaml
linker_script: link.ld
dut_include_dir: .
include_priv_tests: True