name: Reference Implementations

on: [push, pull_request]

jobs:
  impl_ice40:
    name: iCE40 Reference Implementation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: oss-cad-suite
        uses: YosysHQ/setup-oss-cad-suite@v3
        with:
          version: '2024-02-02'

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: pip packages
        run: pip3 install -r requirements.txt

      - name: fusesoc library
        run: |
          fusesoc library add fazyrv .
          fusesoc library add fsoc .

      - name: Run implementation
        run: |
          make report.soc.all TARGET_ARCH=ice40
          make report.md TARGET_ARCH=ice40 >> $GITHUB_STEP_SUMMARY

  impl_ecp5:
    name: ECP5 Reference Implementation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: oss-cad-suite
        uses: YosysHQ/setup-oss-cad-suite@v3
        with:
          version: '2024-02-02'

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: pip packages
        run: pip3 install -r requirements.txt

      - name: fusesoc library
        run: |
          fusesoc library add fazyrv .
          fusesoc library add fsoc .

      - name: Run implementation
        run: |
          make report.soc.all TARGET_ARCH=ecp5
          make report.md TARGET_ARCH=ecp5 >> $GITHUB_STEP_SUMMARY

