name: Lint FazyRV

on: [push, pull_request]

jobs:
  lint_svlint:
    name: Lint using svlint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
  
    - name: Install svlint
      run: sudo snap install svlint

    - name: Linting with svlint
      run: make lint.svlint >> $GITHUB_STEP_SUMMARY
