name: Lint FazyRV

on:
  push:
    branches:
      - main
      - dev

jobs:
  lint_slang:
    name: Lint using slang
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Clone slang
      uses: actions/checkout@v4
      with:
        repository: MikePopoloski/slang
        path: slang

    - name: Install slang
      run: |
        wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
        sudo add-apt-repository "deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-17 main"
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test
        sudo apt-get update
        sudo apt-get install -y g++-13 g++-11 clang-17 clang-tidy-17
        cd slang && cmake -B build && cmake --build build -j8 && cd ..

    - name: Linting with slang
      run: make SLANG=slang/build/bin/slang lint.slang

  lint_svlint:
    name: Lint using svlint
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
  
    - name: Install svlint
      run: sudo snap install svlint

    - name: Linting with slang
      run: make lint.svlint
