name: Track area demand in readme

on:
  push:
    branches:
      - dev
  pull_request:

jobs:
  evaluate:
    name: Run synthesis and upload plot
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: oss-cad-suite
        uses: YosysHQ/setup-oss-cad-suite@v3

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: pip packages
        run: pip install -r requirements.txt

      - name: fusesoc library
        run: |
          fusesoc library add fazyrv .
          fusesoc library add fsoc .

      - name: Actions checkout
        uses: actions/checkout@v3

      - name: Run implementation
        run: make track.sizes.synth COMMIT=$(git rev-parse --short "$GITHUB_SHA")

      - name: Plot artifact
        uses: actions/upload-artifact@v4
        with:
          name: area_plot
          path: './doc/area*'

  commit:
    name: Commit updates
    runs-on: ubuntu-latest
    needs: evaluate
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: actions/download-artifact@v4.1.7

      - name: Copy to docs
        run: |
          cp area_plot/area.svg doc/area.svg
          cp area_plot/area.txt doc/area.txt

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Automated area tracking'
          file_pattern: 'doc/area*'
