name: Track area demand in readme

on: [push, pull_request]

jobs:
  evaluate:
    name: Run synthesis and upload plot
    runs-on: prunner
    steps:
      - name: OSS-CAD-Suite version
        run: echo "oss_url=https://github.com/YosysHQ/oss-cad-suite-build/releases/download/$(date -d "yesterday" "+%Y-%m-%d")/oss-cad-suite-linux-x64-$(date -d "yesterday" "+%Y%m%d").tgz" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: pip packages
        run: pip install -r requirements.txt

      - name: fusesoc library
        run: |
          fusesoc library add fazyrv .
          fusesoc library add fsoc .

      - name: Actions checkout
        uses: actions/checkout@v3

      - name: OSS CAD Suite
        uses: ./.github/workflows/setup-oss-cad
        with:
          from_url: ${{ env.oss_url }}

      - name: Run implementation
        run: make track.sizes.synth COMMIT=$(git rev-parse --short "$GITHUB_SHA")

      - name: Plot artifact
        uses: actions/upload-artifact@v3
        with:
          name: area_plot
          path: './doc/area*'

  commit:
    name: Commit updates
    runs-on: ubuntu-latest
    needs: evaluate
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: actions/download-artifact@v3

      - name: Copy to docs
        run: |
          cp area_plot/area.svg doc/area.svg
          cp area_plot/area.txt doc/area.txt

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Automated area tracking'
          file_pattern: 'doc/area*'
