name: Verification

on: [push, pull_request]

jobs:
  rvtests:
    name: Run rvtests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: oss-cad-suite
      uses: YosysHQ/setup-oss-cad-suite@v3
      with:
        version: '2024-02-02'

    - name: gcc
      uses: ./.github/workflows/setup-riscv-toolchain

    - name: RISC-V Tests
      run: make report.riscvtests.all TOOLCHAIN_PREFIX=riscv32-unknown-elf-

  riscof:
    name: Run RISCOF tests
    runs-on: ubuntu-latest
    needs: rvtests
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: pip packages
      run: pip install -r requirements.txt

    - name: fusesoc library
      run: |
        fusesoc library add fazyrv .
        fusesoc library add fsoc .

    - name: oss-cad-suite
      uses: YosysHQ/setup-oss-cad-suite@v3
      with:
        version: '2024-02-02'

    - name: gcc
      uses: ./.github/workflows/setup-riscv-toolchain

    - name: sail
      uses: ./.github/workflows/setup-sail

    - name: RISCOF
      run: |
        make riscof.prepare
        make riscof.all

  cov_insn:
    name: Cover insn checks
    runs-on: ubuntu-latest
    needs: rvtests
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: oss-cad-suite
      uses: YosysHQ/setup-oss-cad-suite@v3
      with:
        version: '2024-02-02'

    - name: cov.8
      run: make fv.rvformal.cov.insn.8

    - name: cov.4
      run: make fv.rvformal.cov.insn.4

  cov_reg:
    name: Cover reg checks
    runs-on: ubuntu-latest
    needs: rvtests
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: oss-cad-suite
      uses: YosysHQ/setup-oss-cad-suite@v3
      with:
        version: '2024-02-02'

    - name: cov.8
      run: make fv.rvformal.cov.reg.8

    - name: cov.4
      run: make fv.rvformal.cov.reg.4

  bmc_insn:
    name: BMC insn checks
    runs-on: ubuntu-latest
    needs: rvtests
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: oss-cad-suite
      uses: YosysHQ/setup-oss-cad-suite@v3
      with:
        version: '2024-02-02'

    - name: bmc.8
      run: make fv.rvformal.bmc.insn.8
  
    - name: bmc.4
      run: make fv.rvformal.bmc.insn.4

  bmc_reg:
    name: BMC reg checks
    runs-on: ubuntu-latest
    needs: rvtests
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: oss-cad-suite
      uses: YosysHQ/setup-oss-cad-suite@v3
      with:
        version: '2024-02-02'

    - name: bmc.8
      run: make fv.rvformal.bmc.reg.8

    - name: bmc.4
      run: make fv.rvformal.bmc.reg.4